# Generated by Django 4.2.3 on 2023-07-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customer_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
