# Generated by Django 4.2.3 on 2023-07-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0002_alter_orders_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
